### ISSUE TITLE
Issue 5 for Milestone 3: Training the Model

### ISSUE THREAD

**Issue by Haayo1** [Haayo1/Improving-food-production-among-small-scale-farmers-through-Efficient-Resource-Utilization#5]
- [x] Data splitting
- [x] Bootstrapping
- [x] Cross-validation (basic, repeated, or LOOCV)
- [x] Model training for classification
- [x] Model performance comparison using resamples (for classification)
